In [1]:
2 * 3 

6

In [2]:
import numpy as np

In [16]:
a=np.array([5,6,9]) # Array created
a.ndim

1

In [7]:
a[0]

5

In [8]:
a[1]

6

In [11]:
a=np.array([[1,2],[3,4],[5,6]])

In [12]:
a[0]

array([1, 2])

In [13]:
a[0][1]

2

In [15]:
a.ndim # In order to display the dimension

2

In [23]:
a.itemsize

8

In [18]:
a=np.array([[1.1,2.2],[3.5,4.6],[5.2,6.7]])

In [20]:
a.itemsize # Float occuupies 8 bytes

8

In [24]:
a.dtype

dtype('float64')

In [25]:
a=np.array([[1,2],[3,4],[5,6]])
a.itemsize # Int ocuupies 4 bytes

4

In [26]:
a.dtype

dtype('int32')

In [27]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a.dtype

dtype('float64')

In [28]:
a.itemsize

8

In [29]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [30]:
a.size # Total no. of elements

6

In [31]:
a.shape #(No. of rows, No. of columns)

(3, 2)

In [32]:
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [36]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a=np.zeros((3,4)) # No. of rows = 3, No. of columns =4
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
a=np.ones((3,4))

In [38]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
l = range(5)

In [40]:
l

range(0, 5)

In [41]:
l[0]

0

In [42]:
l[4]

4

In [45]:
np.arange(1,5) # Array Range

array([1, 2, 3, 4])

In [46]:
np.arange(1,5,2) # Array Range with step count

array([1, 3])

In [47]:
np.linspace(1,5,2) # Generates 2 numbers between 1 and 5

array([1., 5.])

In [48]:
np.linspace(1,5,20) # Generates 20 numbers between 1 and 5

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [49]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a.shape

(3, 2)

In [50]:
a.reshape(2,3) # You can also reshape provided the current dimensions are compatible with the initial dimensions

array([[1., 2., 3.],
       [4., 5., 6.]])

In [51]:
a.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [52]:
a.reshape(1,6)

array([[1., 2., 3., 4., 5., 6.]])

In [53]:
a.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [54]:
a.ravel() # Flatten the array, i.e. make it one dimensional

array([1., 2., 3., 4., 5., 6.])

In [55]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
a.ravel() # Flatten the array, i.e. make it one dimensional. It only returns new array and it does not modify the original array

array([1, 2, 3, 4, 5, 6])

In [57]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
a.min() # Smallest element

1

In [59]:
a.max()

6

In [60]:
a.sum()

21

In [62]:
a.sum(axis=0) # Returns sum (vertically)

array([ 9, 12])

In [63]:
a.sum(axis=1) # Returns sum (horizontally)

array([ 3,  7, 11])

In [64]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [65]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
np.std(a) # Standard Deviation

1.707825127659933

In [67]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [68]:
a

array([[1, 2],
       [3, 4]])

In [69]:
b

array([[5, 6],
       [7, 8]])

In [70]:
a+b

array([[ 6,  8],
       [10, 12]])

In [71]:
a-b

array([[-4, -4],
       [-4, -4]])

In [72]:
a*b

array([[ 5, 12],
       [21, 32]])

In [73]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [74]:
a.dot(b) # Matrix Product

array([[19, 22],
       [43, 50]])